#define __STAR__COLOR__C__

#include "main.h"
#include "starColor.h"

/// Part 1. OLED/LED/PuTTY 글자색 설정 구간
const char COLOR_keys[] = {'r', 'o', 'y', 'l', 'g', 't', 'c', 's', 'b', 'v', 'm', 'p', 'w', 'k',
		                   'R', 'O', 'Y', 'L', 'G', 'T', 'C', 'S', 'B', 'V', 'M', 'P', 'W', 'K'};

const uint32_t LED_colors[] = {
	COLOR_LED_LIN_R,
	COLOR_LED_LIN_O,
	COLOR_LED_LIN_Y,
	COLOR_LED_LIN_L,
	COLOR_LED_LIN_G,
	COLOR_LED_LIN_T,
	COLOR_LED_LIN_C,
	COLOR_LED_LIN_S,
	COLOR_LED_LIN_B,
	COLOR_LED_LIN_V,
	COLOR_LED_LIN_M,
	COLOR_LED_LIN_P,
	COLOR_LED_LIN_W,
	COLOR_LED_LIN_K,
	COLOR_LED_LIN_R1,
	COLOR_LED_LIN_O1,
	COLOR_LED_LIN_Y1,
	COLOR_LED_LIN_L1,
	COLOR_LED_LIN_G1,
	COLOR_LED_LIN_T1,
	COLOR_LED_LIN_C1,
	COLOR_LED_LIN_S1,
	COLOR_LED_LIN_B1,
	COLOR_LED_LIN_V1,
	COLOR_LED_LIN_M1,
	COLOR_LED_LIN_P1,
	COLOR_LED_LIN_W1,
	COLOR_LED_LIN_K1,
};

const uint32_t LED_darkcolors[] = {
	COLOR_LED_LIN_DR,
	COLOR_LED_LIN_DO,
	COLOR_LED_LIN_DY,
	COLOR_LED_LIN_DL,
	COLOR_LED_LIN_DG,
	COLOR_LED_LIN_DT,
	COLOR_LED_LIN_DC,
	COLOR_LED_LIN_DS,
	COLOR_LED_LIN_DB,
	COLOR_LED_LIN_DV,
	COLOR_LED_LIN_DM,
	COLOR_LED_LIN_DP,
	COLOR_LED_LIN_DW,
	COLOR_LED_LIN_DK,
	COLOR_LED_LIN_DR1,
	COLOR_LED_LIN_DO1,
	COLOR_LED_LIN_DY1,
	COLOR_LED_LIN_DL1,
	COLOR_LED_LIN_DG1,
	COLOR_LED_LIN_DT1,
	COLOR_LED_LIN_DC1,
	COLOR_LED_LIN_DS1,
	COLOR_LED_LIN_DB1,
	COLOR_LED_LIN_DV1,
	COLOR_LED_LIN_DM1,
	COLOR_LED_LIN_DP1,
	COLOR_LED_LIN_DW1,
	COLOR_LED_LIN_DK1,
};

const uint32_t OLED_colors[] = {
	COLOR_OLED_LIN_R,
	COLOR_OLED_LIN_O,
	COLOR_OLED_LIN_Y,
	COLOR_OLED_LIN_L,
	COLOR_OLED_LIN_G,
	COLOR_OLED_LIN_T,
	COLOR_OLED_LIN_C,
	COLOR_OLED_LIN_S,
	COLOR_OLED_LIN_B,
	COLOR_OLED_LIN_V,
	COLOR_OLED_LIN_M,
	COLOR_OLED_LIN_P,
	COLOR_OLED_LIN_W,
	COLOR_OLED_LIN_K,
	COLOR_OLED_LIN_R1,
	COLOR_OLED_LIN_O1,
	COLOR_OLED_LIN_Y1,
	COLOR_OLED_LIN_L1,
	COLOR_OLED_LIN_G1,
	COLOR_OLED_LIN_T1,
	COLOR_OLED_LIN_C1,
	COLOR_OLED_LIN_S1,
	COLOR_OLED_LIN_B1,
	COLOR_OLED_LIN_V1,
	COLOR_OLED_LIN_M1,
	COLOR_OLED_LIN_P1,
	COLOR_OLED_LIN_W1,
	COLOR_OLED_LIN_K1,
};

const uint32_t OLED_darkcolors[] = {
	COLOR_OLED_LIN_DR,
	COLOR_OLED_LIN_DO,
	COLOR_OLED_LIN_DY,
	COLOR_OLED_LIN_DL,
	COLOR_OLED_LIN_DG,
	COLOR_OLED_LIN_DT,
	COLOR_OLED_LIN_DC,
	COLOR_OLED_LIN_DS,
	COLOR_OLED_LIN_DB,
	COLOR_OLED_LIN_DV,
	COLOR_OLED_LIN_DM,
	COLOR_OLED_LIN_DP,
	COLOR_OLED_LIN_DW,
	COLOR_OLED_LIN_DK,
	COLOR_OLED_LIN_DR1,
	COLOR_OLED_LIN_DO1,
	COLOR_OLED_LIN_DY1,
	COLOR_OLED_LIN_DL1,
	COLOR_OLED_LIN_DG1,
	COLOR_OLED_LIN_DT1,
	COLOR_OLED_LIN_DC1,
	COLOR_OLED_LIN_DS1,
	COLOR_OLED_LIN_DB1,
	COLOR_OLED_LIN_DV1,
	COLOR_OLED_LIN_DM1,
	COLOR_OLED_LIN_DP1,
	COLOR_OLED_LIN_DW1,
	COLOR_OLED_LIN_DK1,
};

const uint32_t PuTTY_colors[] = {
	COLOR_PuTTY_R,
	COLOR_PuTTY_O,
	COLOR_PuTTY_Y,
	COLOR_PuTTY_L,
	COLOR_PuTTY_G,
	COLOR_PuTTY_T,
	COLOR_PuTTY_C,
	COLOR_PuTTY_S,
	COLOR_PuTTY_B,
	COLOR_PuTTY_V,
	COLOR_PuTTY_M,
	COLOR_PuTTY_P,
	COLOR_PuTTY_W,
	COLOR_PuTTY_K,
	COLOR_PuTTY_R1,
	COLOR_PuTTY_O1,
	COLOR_PuTTY_Y1,
	COLOR_PuTTY_L1,
	COLOR_PuTTY_G1,
	COLOR_PuTTY_T1,
	COLOR_PuTTY_C1,
	COLOR_PuTTY_S1,
	COLOR_PuTTY_B1,
	COLOR_PuTTY_V1,
	COLOR_PuTTY_M1,
	COLOR_PuTTY_P1,
	COLOR_PuTTY_W1,
	COLOR_PuTTY_K1,
};

const uint32_t PuTTY_darkcolors[] = {
	COLOR_PuTTY_DR,
	COLOR_PuTTY_DO,
	COLOR_PuTTY_DY,
	COLOR_PuTTY_DL,
	COLOR_PuTTY_DG,
	COLOR_PuTTY_DT,
	COLOR_PuTTY_DC,
	COLOR_PuTTY_DS,
	COLOR_PuTTY_DB,
	COLOR_PuTTY_DV,
	COLOR_PuTTY_DM,
	COLOR_PuTTY_DP,
	COLOR_PuTTY_DW,
	COLOR_PuTTY_DK,
	COLOR_PuTTY_DR1,
	COLOR_PuTTY_DO1,
	COLOR_PuTTY_DY1,
	COLOR_PuTTY_DL1,
	COLOR_PuTTY_DG1,
	COLOR_PuTTY_DT1,
	COLOR_PuTTY_DC1,
	COLOR_PuTTY_DS1,
	COLOR_PuTTY_DB1,
	COLOR_PuTTY_DV1,
	COLOR_PuTTY_DM1,
	COLOR_PuTTY_DP1,
	COLOR_PuTTY_DW1,
	COLOR_PuTTY_DK1,
};

/// @desc : 컬러 팔레트 배열 포인터 출력 함수.
const uint32_t * COLOR_palletes[] = {LED_colors, LED_darkcolors, OLED_colors, OLED_darkcolors, PuTTY_colors, PuTTY_darkcolors};


/// @desc : 컬러 팔레트 입력하여 색상 출력하는 함수
int32_t FindColor(char key, const uint32_t * pallete){
	for(uint8_t i = 0; i < sizeof(COLOR_keys) / sizeof(char); i++){
		if(COLOR_keys[i] == key){
			return pallete[i];
		}
	}
	return -1;
}

/// Part 2. Default Colors
uint32_t COLOR_default[4] = {COLOR_DEF_1, COLOR_DEF_2, COLOR_DEF_3, COLOR_DEF_4};


